SELECT 
APPLICATION_NAME,APPLICATION_SHORT_NAME,
BASEPATH,DESCRIPTION,APPLICATION_ID,
LAST_UPDATE_LOGIN,CREATED_BY,CREATION_DATE,
LAST_UPDATE_DATE,LAST_UPDATED_BY,ROW_ID 
FROM FND_APPLICATION_VL  order by application_name
/
